// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model;

namespace YunPanCore.Migrations
{
    [DbContext(typeof(YunPanContext))]
    [Migration("20191121071206_init_store")]
    partial class init_store
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Model.FileInfo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40);

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(40);

                    b.Property<DateTime>("ChangedDate");

                    b.Property<DateTime?>("CreateDate")
                        .IsRequired();

                    b.Property<DateTime?>("DeleteDate");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(248);

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("FileSize")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("HashCode")
                        .HasMaxLength(40);

                    b.Property<int>("IsDeleted");

                    b.Property<string>("MapPath")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<int>("Shared");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.ToTable("FileInfo");
                });

            modelBuilder.Entity("Model.SharedFileInfo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40);

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(40);

                    b.Property<DateTime>("ChangedDate");

                    b.Property<DateTime?>("CreateDate")
                        .IsRequired();

                    b.Property<DateTime?>("DeleteDate");

                    b.Property<string>("FileId")
                        .HasMaxLength(40);

                    b.Property<int>("IsDeleted");

                    b.Property<string>("OwnerName")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("SharedFileInfo");
                });

            modelBuilder.Entity("Model.UserDataInfo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40);

                    b.Property<int>("Age");

                    b.Property<string>("Cap")
                        .HasMaxLength(64);

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(40);

                    b.Property<DateTime>("ChangedDate");

                    b.Property<DateTime?>("CreateDate")
                        .IsRequired();

                    b.Property<DateTime?>("DeleteDate");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(50);

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Gender");

                    b.Property<int>("IsDeleted");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Phone")
                        .HasMaxLength(40);

                    b.Property<string>("Remark")
                        .HasMaxLength(233);

                    b.Property<string>("Stored")
                        .HasMaxLength(64);

                    b.Property<string>("UserAccount")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("UserType")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("UserAccount")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("UserDataInfo");
                });

            modelBuilder.Entity("Model.FileInfo", b =>
                {
                    b.HasOne("Model.UserDataInfo", "Owner")
                        .WithMany("UserFiles")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Model.SharedFileInfo", b =>
                {
                    b.HasOne("Model.FileInfo", "UserFile")
                        .WithMany("SharedFiles")
                        .HasForeignKey("FileId");
                });
#pragma warning restore 612, 618
        }
    }
}
